name: Deploy Dockerized React App to ECS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging  # Optionally track other branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t jules333/myapp:$GITHUB_SHA .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push jules333/myapp:$GITHUB_SHA

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install AWS ECS CLI
      run: |
        sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
        sudo chmod +x /usr/local/bin/ecs-cli

    - name: Deploy to ECS
      run: |
        ecs-cli configure --region us-east-2 --cluster practicereactdocker
        ecs-cli compose --file docker-compose.yml up
